version: '3.8'

services:
  swi_cache:
    image: lpauchet/swi-server:latest
    ports:
      - "5000:5000"
    volumes:
      - ./docker_volume/cache:/app/cache
      - ./docker_volume/maps:/app/maps
    env_file:
      - .env
    environment:
      - SWI_INSTANCE_SERVE_ONLY=false
      - SWI_DOCKER_INSTANCE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  swi_serve:
    image: lpauchet/swi-server:latest
    ports:
      - "5001:5000"
    volumes:
      - ./docker_volume/cache:/app/cache
      - ./docker_volume/maps:/app/maps
    environment:
      - SWI_INSTANCE_SERVE_ONLY=true
      - SWI_DOCKER_INSTANCE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
