services:
  swi_cache:
    image: lpauchet/swi-server:latest
    volumes:
      - ./cache:/app/cache
      - ./maps:/app/maps
    env_file:
      - .env
    environment:
      - SWI_INSTANCE_SERVE_ONLY=false
      - SWI_DOCKER_INSTANCE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - swi_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swi_serve1:
    image: lpauchet/swi-server:latest
    volumes:
      - ./cache:/app/cache
      - ./maps:/app/maps
    environment:
      - SWI_INSTANCE_SERVE_ONLY=true
      - SWI_DOCKER_INSTANCE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - swi_network

  swi_serve2:
    image: lpauchet/swi-server:latest
    volumes:
      - ./cache:/app/cache
      - ./maps:/app/maps
    environment:
      - SWI_INSTANCE_SERVE_ONLY=true
      - SWI_DOCKER_INSTANCE=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - swi_network

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - swi_serve1
      - swi_serve2
    networks:
      - swi_network

networks:
  swi_network:
    driver: bridge