site_name: Svalbard Weather Information

docs_dir: docs
site_url: https://swi-svalbard-weather-information.readthedocs.io/en/latest/
repo_url: https://github.com/LouisPauchet/UNIS_SvalbardWeatherInformation
repo_name: LouisPauchet/UNIS_SvalbardWeatherInformation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tabs.sticky
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy  # Ensure this feature is enabled for copy buttons

  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
  - git-revision-date-localized:
      enable_creation_date: true
  - git-authors
  - glightbox  # Add this plugin for better image and iframe handling

nav:
  - Home: index.md
  - User:
      - Introduction: user/intro.md
      - Avalanche Forecasting: user/avalanche_forecast.md
  - Administrator:
      - Introduction: admin/intro.md
      - Deployment: admin/deployment.md
  - API:
      - AW Stations Endpoints: api.md
  - Backend Codebase:
      - Cache Handler: backend/cacheHandler.md
      - Config Handler: backend/confighandler.md
      - Datasource: backend/datasource.md
      - Logger: backend/logger.md
      - Maps Processing: backend/maps_processing.md

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.