site_name: Svalbard Weather Information
docs_dir: docs
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - content.code.annotate
    - content.tabs.link


plugins:
  - search
  - mkdocstrings:
      default_handler: python

nav:
  - Home: index.md
  - API:
      #- App: api/app_api.md
      - Cache Handler: api/cacheHandler.md
      - Config Handler: api/confighandler.md
      - Datasource: api/datasource.md
      - Logger: api/logger.md
      - Maps Processing: api/maps_processing.md
