site_name: Documentation - Svalbard Weather Information
site_url: https://swi-docs.yourdomain.com/
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - API Reference:
      - Python: api/python.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: false
            extra:
              paths: [../source]
