name: Deploy

on:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Increment version
      id: version
      run: |
        # Read the version components
        VERSION_NAME=$(head -n 1 version)
        BUILD_NUMBER=$(head -n 2 version | tail -n 1)
        STATE=$(tail -n 1 version)

        # Increment the build number
        IFS='.' read -r -a build_parts <<< "$BUILD_NUMBER"
        NEW_BUILD_NUMBER="${build_parts[0]}.${build_parts[1]}.$((${build_parts[2]} + 1))"

        # Update the version file with the new build number
        sed -i "2s/.*/$NEW_BUILD_NUMBER/" version

        # Set the new version as an environment variable
        echo "NEW_VERSION=$VERSION_NAME $NEW_BUILD_NUMBER $STATE" >> $GITHUB_ENV
        echo "NEW_BUILD_NUMBER=$NEW_BUILD_NUMBER" >> $GITHUB_ENV

    - name: Commit version increment
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add version
        git commit -m "Increment version to $NEW_BUILD_NUMBER"
        git push

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: lpauchet/swi-server:${{ env.NEW_BUILD_NUMBER }}

    - name: Create Pre-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_BUILD_NUMBER }}-alpha
        release_name: Release v${{ env.NEW_BUILD_NUMBER }}-alpha
        body: |
          Changes in this release:
          - Incremented version to ${{ env.NEW_BUILD_NUMBER }}
        draft: false
        prerelease: true
