name: Create Pre-release

on:
  push:
    branches:
      - master
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed

jobs:
  create-pre-release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get previous tag
        id: get_previous_tag
        run: |
          previous_tag=$(git describe --tags --match "1.0.*" --abbrev=0 2>/dev/null || echo "1.0.0")
          echo "PREVIOUS_TAG=\$previous_tag" >> $GITHUB_ENV

      - name: Calculate new tag
        id: calculate_new_tag
        run: |
          IFS='.' read -r -a version_parts <<< "${{ env.PREVIOUS_TAG }}"
          new_patch_version=\$((version_parts[2] + 1))
          new_tag="1.0.\$new_patch_version"
          echo "NEW_TAG=\$new_tag" >> $GITHUB_ENV

      - name: Read version file
        id: read_version_file
        run: |
          version_name=$(awk 'NR==1' version)
          version_state=\$(awk 'NR==3' version || echo "")
          echo "VERSION_NAME=\$version_name" >> \$GITHUB_ENV
          echo "VERSION_STATE=\$version_state" >> $GITHUB_ENV

      - name: Update version file
        run: |
          sed -i "2s/.*/${{ env.NEW_TAG }}/" version

      - name: Commit version file
        run: |
          git add version
          git commit -m "Update version file to ${{ env.NEW_TAG }}"
          git push origin master

      - name: Create pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: |
            Release ${{ env.VERSION_NAME }} ${{ env.NEW_TAG }} ${{ env.VERSION_STATE && format('{0}', env.VERSION_STATE) || '' }}
          body: Automated pre-release for commit \${{ github.sha }}
          draft: true
          prerelease: true