name: Run Tests with pytest

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests without live tests
        run: pytest --cov=. --cov-report=xml --cov-report=term --ignore-glob='*live*.py' --maxfail=1 --exitfirst

      - name: Debug - List all files before uploading coverage
        run: ls -R

      - name: Check if coverage report exists
        run: |
          if [ -f coverage.xml ]; then
            echo "Coverage report found."
          else
            echo "ERROR: coverage.xml not found!"
            exit 1
          fi

      - name: Upload coverage report as GitHub Artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.python-version }}
          path: "**/coverage.xml"
